# These environment variables must be set in CircleCI UI
#
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#
# Read the README for more information.
version: 2
jobs:
  build:
    environment:
      GOPATH_HEAD: "$(echo $GOPATH | cut -d ':' -f 1)"
      GOPATH_BASE: "$GOPATH_HEAD/src/github.com/$CIRCLE_PROJECT_USERNAME"
      GO15VENDOREXPERIMENT: 1
      DOCKER_REPO: "$(if [ $CIRCLE_PROJECT_USERNAME == 'Securing-DevOps' ]; then echo securingdevops; else echo $DOCKER_USER; fi)"

    steps:
      - checkout
      - setup_remote_docker


      - run:
          command: |
            rm -rf ${GOPATH_BASE}/;
            mkdir -p "$GOPATH_BASE";
            mkdir -p "$GOPATH/bin";
            cp -r ${HOME}/${CIRCLE_PROJECT_REPONAME} ${GOPATH_BASE}/;
            go get github.com/govend/govend;
            sudo pip install awscli;

      - run:
          command: |
            go test github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
            mkdir -P bin;
            cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/deployer;
            chmod +x deploymentTests/*;
            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;

      - run:
          command: |
            docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS};
            docker images --no-trunc | awk '/^app/ {print $3}' | tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
            docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}

      #-run:
      #  - command: |    # trigger ebs redeploy
          #- aws elasticbeanstalk update-environment --region us-east-1 --application-name invoicer201707071231 --environment-id e-h4vyur8nup --version-label deployer-api
